# -*- coding: utf-8 -*-
"""curso basico python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13MglOPeR_XhJG34aA9vQ9Ke6Zs13Emji
"""

import os
import pandas as pd
import plotly.express as px


#os.listdir serve pra listar um diretório que é a mesma coisa que uma pasta
lista_arquivo = os.listdir('/content/drive/MyDrive/curso basico python/Vendas')
#display(lista_arquivo)

                  #importar as bases de dados de vendas
  #estrutura de repetição e format

# o for ele serve basicamente pra passar o codigo pro proximo item/arquivo

   #estuturas de condição e textos

#estrutura de condição: if e else

tabela_total = pd.DataFrame()




for arquivo in lista_arquivo:
  if "Vendas" in arquivo:
    #importar o arquivo
    tabela = pd.read_csv(f'/content/drive/MyDrive/curso basico python/Vendas/{arquivo}')
    #tratamento e compilação das bases de dados
    tabela_total = tabela_total.append(tabela)

display (tabela_total)

#calculo de indicadores e gráficos

#calcular o produto mais vendido(em quantidade)

#agrupar os produtos e somar os valores


tabela_produtos = tabela_total.groupby("Produto").sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida", "Preco Unitario"]].sort_values(by= "Quantidade Vendida", ascending = False)
display(tabela_produtos)

#calcular o produto mais vendido(em faturamento)
#criar uma nova coluna

tabela_total["Faturamento"] = tabela_total["Quantidade Vendida"] * tabela_total["Preco Unitario"]



tabela_faturamento = tabela_total.groupby("Produto").sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by= "Faturamento", ascending = False)
display(tabela_faturamento)

#calcular a loja/cidade que mais vendeu

tabela_lojas = tabela_total.groupby("Loja").sum()
tabela_lojas = tabela_lojas[["Faturamento"]]
display(tabela_lojas)

#criando um grafico

grafico = px.bar (tabela_lojas, x = tabela_lojas.index, y = "Faturamento")
grafico.show()
#o indice da sua tabela tem que ser escrito daquele jeito, nao da so pra por o nomeda coluna. o indice da tabela e o que ta em negrito